# Site settings
title: Errol Hinkamp
email: ehinkamp87@gmail.com
url: https://ehinkamp.github.io
description: "Errol Hinkamp's data analysis portfolio."
keywords: "Data, analysis, visualization, analytics"
skills: "Junior Data Analyst"
meta_author: Hinkamp Errol

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static
email: mvolojbq

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 4682B4 #80B3FF
  primary-rgb: "70,130,180" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Errol Hinkamp
  credits: Credits
  location: Location
  social: Around the Web
  
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/errolhinkamp/
#  - title: 
#    url:
#  - title: 
#    url: 
#  - title: 
#    url: 
  - title: github
    url: https://github.com/ehinkamp

# Postal address (add as many lines as necessary)
address:
  - line: Melbourne Beach, FL 32951

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
